#! /bin/sh
# set monitor order
#set -U SXHKD_SHELL /usr/bin/bash
sxhkd &

# monitor config -- set numbers here for desktop shift control
bspc monitor DP-4 -n 1 -d web ide four five six seven eight media
bspc monitor HDMI-0 -n 2 -d one social

#bspc desktop social -m HDMI-0

#styling config
bspc config border_width         2
bspc config window_gap          12

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='web'
bspc rule -a Screenkey manage=off

bspc rule -a Telegram desktop='social'
bspc rule -a Signal desktop='social'
bspc rule -a TelegramDesktop desktop='social'
bspc rule -a Slack desktop='social'
bspc rule -a Emacs state=tiled
### AutoStart
compton &

pa-applet &
nm-applet &
polybar primary &
#polybar secondary &

#wal -i $HOME/wall/glitch-rainbow.jpg


#apply wal styles to bspwm

#. "${HOME}/.cache/wal/colors.sh"

#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
## Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
## Use the line below if you are on bspwm < 0.9.4
##bspc config presel_border_color "$color1"

# adopt any orphans
bspc wm --adopt-orphans
bash "$HOME/.config/bspwm/bspwm_colors.sh" &
wpg -m
xmodmap ~/.Xmodmap
urxvt
